version: '3'
networks:
    covid-network: 
        driver: bridge
services:
    ui:
        build: ./covid-dashboard-ui/
        image: ga7uti/coviddashboardui:latest
        ports: 
            - 4200:80
        networks: 
            - covid-network

    vaccineservice:
        build: ./covid-vaccine-service/
        image: ga7uti/vaccineservice:latest
        ports: 
            - 9090:9090
        networks: 
            - covid-network

    countryservice:
        build: ./country-service/
        image: ga7uti/countryservice:latest
        ports: 
            - 9091:9091
        networks: 
            - covid-network
